project_id = "euciggcpwyuctelogciv"

[functions.create-reservation]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.send-reservation-email]
verify_jwt = false

[functions.cancel-reservation]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.admin-actions]
verify_jwt = false

[functions.modify-reservation]
verify_jwt = false

[functions.auto-cancel-overdue]
verify_jwt = false

