project_id = "euciggcpwyuctelogciv"

[functions.create-reservation]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.send-reservation-email]
verify_jwt = false

[functions.cancel-reservation]
verify_jwt = false
